language: python
sudo: true
python:
    - "2.7"
services:
  - docker
install:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt

script:
  - "docker run -i -v \"${PWD}:/OpenBazaar\" toopher/ubuntu-i386:14.04 /bin/bash -c \"linux32 --32bit i386 /OpenBazaar/build.sh\""
  - sudo bash build-win.sh
  - sudo bash build-win64.sh
  - sudo chmod 777 dist/openbazaard-linux32
  - sudo chmod 777 dist/openbazaard.exe
after_success:
    - coveralls
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file:
    - "dist/openbazaard-linux32"
    - "dist/openbazaard.exe"
  skip_cleanup: true
  on:
    all_branches: true
